AllCops:
  Exclude:
    - 'Vagrantfile'
    - 'Thorfile'
    - 'Gemfile'
    - 'metadata.rb'
    - 'spec/**'
    - 'test/**'

Encoding:
  Enabled: false

LineLength:
  Max: 99

SingleSpaceBeforeFirstArg:
  Enabled: false
